CREATE DATABASE weather_stations_api;

CREATE TABLE stations (
    id INTEGER NOT NULL,
    ws_name TEXT NOT NULL,
    site TEXT NOT NULL,
    portfolio TEXT NOT NULL,
    state TEXT NOT NULL,
    latitude DOUBLE PRECISION NOT NULL,
    longitude DOUBLE PRECISION NOT NULL
);

CREATE TABLE variables (
    var_id INTEGER NOT NULL,
    id INTEGER NOT NULL,
    name TEXT NOT NULL,
    unit TEXT NOT NULL,
    long_name TEXT NOT NULL
);

CREATE TABLE data_1 (
    id SERIAL PRIMARY KEY,
    value1 DOUBLE PRECISION NOT NULL,
    value2 DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE data_2 (
    id SERIAL PRIMARY KEY,
    value1 DOUBLE PRECISION NOT NULL,
    value2 DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE data_3 (
    id SERIAL PRIMARY KEY,
    value1 DOUBLE PRECISION NOT NULL,
    value2 DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE data_4 (
    id SERIAL PRIMARY KEY,
    value1 DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE data_5 (
    id SERIAL PRIMARY KEY,
    value1 DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE data_6 (
    id SERIAL PRIMARY KEY,
    value1 DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE data_7 (
    id SERIAL PRIMARY KEY,
    value1 DOUBLE PRECISION NOT NULL,
    value2 DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE data_8 (
    id SERIAL PRIMARY KEY,
    value1 DOUBLE PRECISION NOT NULL,
    value2 DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE data_9 (
    id SERIAL PRIMARY KEY,
    value1 DOUBLE PRECISION NOT NULL,
    value2 DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);

CREATE TABLE data_10 (
    id SERIAL PRIMARY KEY,
    value1 DOUBLE PRECISION NOT NULL,
    value2 DOUBLE PRECISION NOT NULL,
    timestamp TEXT NOT NULL
);